version: '3.8'

services:
  db:
    container_name: pets_db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pets_db
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    networks:
     - msnetwork

networks:
  msnetwork:
    driver: bridge